###################### Base Settings######################
test_during_training: True

### database ###
EuroSat:
  datainfo: C:/Users/win 10/Desktop/FR_IQA/IQA-optimization/Artif_MOS.csv
  im_dir: C:/Users/win 10/Desktop/FR_IQA/IQA-optimization/Destorted_images

patch_size: 32
stride: 32

train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
CNNIQA :
  n1_kernels: 8
  n2_kernels: 50
  kernel_size: 3
  pool_size: 2
  n1_nodes: 128
  n2_nodes: 512
  alpha_q: 0.5
  alpha_d: 0.5